name: Update Lean
on:
  schedule:
    # 毎日実行
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  update_lean:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'lean-ja'
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Update Lean project
        uses: leanprover-community/lean-update@develop
        with:
          update_if_modified: lean-toolchain
          build_args: "--log-level=warning --fail-level=warning"
